// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nexus.Patients.Api.Infrastructure.Persistence;

#nullable disable

namespace Nexus.Patients.Api.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PatientDbContext))]
    [Migration("20260528222846_AddPatientCoreFields")]
    partial class AddPatientCoreFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Nexus.Patients.Api.Features.Patients.Models.Patient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AddressLine1")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("AddressLine2")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("ArchivedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Country")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("PrimaryBranchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PublicCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("State")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.HasKey("Id");

                    b.HasIndex("PublicCode")
                        .IsUnique()
                        .HasDatabaseName("UX_Patients_PublicCode");

                    b.HasIndex("Email", "DateOfBirth")
                        .IsUnique()
                        .HasDatabaseName("UX_Patients_Email_DOB")
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex("Phone", "DateOfBirth")
                        .IsUnique()
                        .HasDatabaseName("UX_Patients_Phone_DOB")
                        .HasFilter("[Phone] IS NOT NULL");

                    b.HasIndex("Status", "ArchivedAtUtc")
                        .HasDatabaseName("IX_Patients_Status_ArchivedAtUtc");

                    b.ToTable("Patients", (string)null);
                });

            modelBuilder.Entity("Nexus.Patients.Api.Features.Patients.Models.PatientBranchLink", b =>
                {
                    b.Property<Guid>("PatientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LinkedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<DateTime?>("UnlinkedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.HasKey("PatientId", "BranchId");

                    b.HasIndex("PatientId", "IsPrimary", "UnlinkedAtUtc")
                        .HasDatabaseName("IX_PatientBranchLinks_PatientId_IsPrimary_Unlinked");

                    b.ToTable("PatientBranchLinks", (string)null);
                });

            modelBuilder.Entity("Nexus.Patients.Api.Features.Patients.Models.PatientCodeSequence", b =>
                {
                    b.Property<string>("BranchCode")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<short>("Year")
                        .HasColumnType("smallint");

                    b.Property<int>("LastValue")
                        .HasColumnType("int");

                    b.HasKey("BranchCode", "Year");

                    b.ToTable("PatientCodeSequences", (string)null);
                });

            modelBuilder.Entity("Nexus.Patients.Api.Infrastructure.Audit.Outbox.PendingAuditEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Attempts")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("LastError")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<DateTime>("NextRetryUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("UX_PendingAudit_IdempotencyKey");

                    b.HasIndex("NextRetryUtc")
                        .HasDatabaseName("IX_PendingAudit_NextRetryUtc");

                    b.ToTable("PendingAuditEntries", (string)null);
                });

            modelBuilder.Entity("Nexus.Patients.Api.Features.Patients.Models.PatientBranchLink", b =>
                {
                    b.HasOne("Nexus.Patients.Api.Features.Patients.Models.Patient", "Patient")
                        .WithMany("BranchLinks")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Nexus.Patients.Api.Features.Patients.Models.Patient", b =>
                {
                    b.Navigation("BranchLinks");
                });
#pragma warning restore 612, 618
        }
    }
}
