// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nexus.Doctors.Api.Infrastructure.Persistence;

#nullable disable

namespace Nexus.Doctors.Api.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(DoctorDbContext))]
    [Migration("20260528202950_InitialDoctorSchema")]
    partial class InitialDoctorSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Nexus.Doctors.Api.Features.Doctors.Models.Doctor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<string>("Email")
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("LicenseAuthority")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Phone")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("PublicCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Specialisation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.HasKey("Id");

                    b.HasIndex("LicenseNumber")
                        .IsUnique()
                        .HasDatabaseName("UX_Doctors_License_Active")
                        .HasFilter("[Status] <> 4");

                    b.HasIndex("PublicCode")
                        .IsUnique()
                        .HasDatabaseName("UX_Doctors_PublicCode");

                    b.ToTable("Doctors", (string)null);
                });

            modelBuilder.Entity("Nexus.Doctors.Api.Features.Doctors.Models.DoctorBranchLink", b =>
                {
                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LinkedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<DateTime?>("UnlinkedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.HasKey("DoctorId", "BranchId");

                    b.HasIndex("DoctorId", "IsPrimary", "UnlinkedAtUtc")
                        .HasDatabaseName("IX_DoctorBranchLinks_DoctorId_IsPrimary_Unlinked");

                    b.ToTable("DoctorBranchLinks", (string)null);
                });

            modelBuilder.Entity("Nexus.Doctors.Api.Features.Doctors.Models.DoctorCodeSequence", b =>
                {
                    b.Property<string>("BranchCode")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<short>("Year")
                        .HasColumnType("smallint");

                    b.Property<int>("LastValue")
                        .HasColumnType("int");

                    b.HasKey("BranchCode", "Year");

                    b.ToTable("DoctorCodeSequences", (string)null);
                });

            modelBuilder.Entity("Nexus.Doctors.Api.Features.Doctors.Models.DoctorDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("ReviewNote")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("ReviewedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<string>("ReviewedByUsername")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("UploadedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId")
                        .HasDatabaseName("IX_DoctorDocuments_DoctorId");

                    b.HasIndex("DoctorId", "Sha256")
                        .IsUnique()
                        .HasDatabaseName("UX_DoctorDocuments_Doctor_Sha")
                        .HasFilter("[DeletedAtUtc] IS NULL");

                    b.ToTable("DoctorDocuments", (string)null);
                });

            modelBuilder.Entity("Nexus.Doctors.Api.Infrastructure.Audit.Outbox.PendingAuditEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Attempts")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("LastError")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<DateTime>("NextRetryUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("UX_PendingAudit_IdempotencyKey");

                    b.HasIndex("NextRetryUtc")
                        .HasDatabaseName("IX_PendingAudit_NextRetryUtc");

                    b.ToTable("PendingAuditEntries", (string)null);
                });

            modelBuilder.Entity("Nexus.Doctors.Api.Features.Doctors.Models.DoctorBranchLink", b =>
                {
                    b.HasOne("Nexus.Doctors.Api.Features.Doctors.Models.Doctor", "Doctor")
                        .WithMany("BranchLinks")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("Nexus.Doctors.Api.Features.Doctors.Models.DoctorDocument", b =>
                {
                    b.HasOne("Nexus.Doctors.Api.Features.Doctors.Models.Doctor", "Doctor")
                        .WithMany("Documents")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("Nexus.Doctors.Api.Features.Doctors.Models.Doctor", b =>
                {
                    b.Navigation("BranchLinks");

                    b.Navigation("Documents");
                });
#pragma warning restore 612, 618
        }
    }
}
